In [2]:
import numpy as np
import pandas as pd

In [ ]:
# Basic stuff
list1 =[[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]]
arr=np.array(list1)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 2 3 4 5]
  [1 2 3 4 5]]]
<class 'numpy.ndarray'>
int64
(1, 2, 5)
3
10


In [17]:
# array of 0 and 1
arr1= np.zeros((2, 2))
print(arr1)

arr2= np.ones((2, 2))
print(arr2)

arr3= np.full((3, 3), fill_value=7)
print(arr3)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [24]:
import random

print(np.random.random()) # Random integer between 0 and 1

arr1= np.random.random((3, 3)) # Random numbers between 0 and 1
print(arr1)

arr2= np.random.randint(1, 10, (3, 3)) # Random integers between 1 and 10
print(arr2)

arr3= np.random.choice([10, 20, 30], size=(3, 3)) # Random number from the list
print(arr3)

arr4= np.random.uniform(5, 10, (3, 3))  # Random float numbers between 5 and 10
print(arr4) 

arr5= np.arange(0, 7, 2)  # [0, 2, 4, 6]  <start, stop, space b/w elements>
print(arr5)

arr6= np.linspace(0, 10, 5)  # [0, 2.5, 5, 7.5, 10] <start, stop, no. of elements>
print(arr6)

0.040016281127026154
[[0.13419478 0.17803305 0.78814018]
 [0.85082525 0.88580464 0.9599583 ]
 [0.39253942 0.53045341 0.02127697]]
[[4 7 4]
 [2 9 5]
 [8 8 2]]
[[10 10 20]
 [20 10 10]
 [20 20 20]]
[[7.34309779 7.46701909 6.47249033]
 [9.62186932 9.68479089 5.1674923 ]
 [6.53680545 7.28603867 6.35132755]]
[0 2 4 6]
[ 0.   2.5  5.   7.5 10. ]


In [32]:
arr1= np.random.random((3, 3)) # Random numbers between 0 and 1
print(arr1)
print(arr1.shape)

arr2= np.reshape(arr1, (1,9))
print(arr2)  # Reshape to 1 row and 9 columns
print(arr2.shape)

arr3= arr1.flatten()  # Flatten the array to 1D
print(arr3)
print(arr3.shape)

[[0.41465082 0.82427944 0.93660023]
 [0.77208517 0.25348163 0.81647835]
 [0.9318625  0.68578838 0.0569873 ]]
(3, 3)
[[0.41465082 0.82427944 0.93660023 0.77208517 0.25348163 0.81647835
  0.9318625  0.68578838 0.0569873 ]]
(1, 9)
[0.41465082 0.82427944 0.93660023 0.77208517 0.25348163 0.81647835
 0.9318625  0.68578838 0.0569873 ]
(9,)


In [ ]:
arr1=np.array([1, 2, 3, 4, 5, 6])
print(arr1)

print(arr1+1)
print(arr1-1)
print(arr1*2)
print(arr1/2)
print(arr1**2)

arr2=np.random.randint(1, 10, (3, 3))
print(arr2)
print(arr2.max())
print(arr2.max(axis=0))  #maximum element column wise

[1 2 3 4 5 6]
[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[ 1  4  9 16 25 36]
[[7 8 7]
 [6 9 4]
 [8 2 6]]
9
[8 9 7]


In [55]:
arr1=np.array([[1, 5, 3],
               [4, 1, 4],
               [8, 6, 6]])
arr2=np.array([[3, 4, 7],
               [3, 2, 8],
               [2, 1, 8]])

print(arr1 + arr2)
print(arr1*arr2)  # element-wise multiplication
print(arr1 @ arr2)  # matrix multiplication
print(np.dot(arr1, arr2))  # dot product

[[ 4  9 10]
 [ 7  3 12]
 [10  7 14]]
[[ 3 20 21]
 [12  2 32]
 [16  6 48]]
[[ 24  17  71]
 [ 23  22  68]
 [ 54  50 152]]
[[ 24  17  71]
 [ 23  22  68]
 [ 54  50 152]]


In [72]:
arr1=np.array([[1, 5, 3],
               [4, 1, 4],
               [8, 6, 6]])

print(arr1[1,:])
print(arr1.shape)

[4 1 4]
(3, 3)


In [76]:
arr1=np.array([[1, 5, 3],
               [4, 1, 4],
               [8, 6, 6]])
arr1=np.sort(arr1, axis=0, kind='mergesort')  # Sorts the array in ascending order
print(arr1)

[[1 1 3]
 [4 5 4]
 [8 6 6]]


In [79]:
arr1= np.random.randint(1, 10, (3, 3)) # Random numbers between 0 and 1
print(arr1)

arr2= np.random.randint(1, 10, (3, 3)) # Random numbers between 0 and 1
print(arr2)

arr3= np.vstack((arr1, arr2))  # Stack arrays vertically
print(arr3)

arr4= np.hstack((arr1, arr2))  # Stack arrays horizontally
print(arr4)

arr5= np.concatenate((arr1, arr2), axis=0)  # Concatenate arrays along the first axis
print(arr5)

arr6= np.concatenate((arr1, arr2), axis=1)  # Concatenate arrays along the second axis      
print(arr6)

[[3 5 4]
 [4 2 2]
 [5 6 9]]
[[9 6 7]
 [4 8 9]
 [8 4 6]]
[[3 5 4]
 [4 2 2]
 [5 6 9]
 [9 6 7]
 [4 8 9]
 [8 4 6]]
[[3 5 4 9 6 7]
 [4 2 2 4 8 9]
 [5 6 9 8 4 6]]
[[3 5 4]
 [4 2 2]
 [5 6 9]
 [9 6 7]
 [4 8 9]
 [8 4 6]]
[[3 5 4 9 6 7]
 [4 2 2 4 8 9]
 [5 6 9 8 4 6]]


**Pandas**
-

In [8]:
list1 = [1, 2, 3]
print(pd.Series( list1))
print(pd.Series([list1, list1]))

0    1
1    2
2    3
dtype: int64
0    [1, 2, 3]
1    [1, 2, 3]
dtype: object


In [11]:
print(pd.DataFrame([list1, list1]))
print(pd.DataFrame([list1, list1], columns=['A', 'B', 'C']))

   0  1  2
0  1  2  3
1  1  2  3
   A  B  C
0  1  2  3
1  1  2  3


In [20]:
df=pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
type(df)

pandas.core.frame.DataFrame

In [18]:
data=pd.read_csv('googleplaystore.csv')

print(data.head())  # Display the first few rows of the DataFrame
print(data.shape)
print(data.columns)  # Display the column names of the DataFrame

                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend 

In [21]:
data.info()  # Display information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10841 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object 
 4   Size            10841 non-null  object 
 5   Installs        10841 non-null  object 
 6   Type            10840 non-null  object 
 7   Price           10841 non-null  object 
 8   Content Rating  10840 non-null  object 
 9   Genres          10841 non-null  object 
 10  Last Updated    10841 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(1), object(12)
memory usage: 1.1+ MB


**OS Lbraries**
-

In [81]:
import os

In [ ]:
# get current working directory
os.getcwd()

'c:\\Users\\AYUSH\\OneDrive\\Desktop\\College\\Interests\\ML\\Data Analysis'

In [ ]:
# make directorie
os.mkdir("GFG")

In [85]:
# make nested directories
os.makedirs("GFG/subdir1")

In [96]:
os.remove("GFG1/subdir1")  # remove file

PermissionError: [WinError 5] Access is denied: 'GFG1/subdir1'

In [87]:
for i in os.listdir():
    print(i)

GFG
Inventory.txt
Inventory_Management(.txt).ipynb
Inventory_Management(JSoN).ipynb
numpy.ipynb
record.json
Sales.txt
Sale_json.txt


In [88]:
os.rename("GFG", "GFG1")  # Rename directory

In [90]:
os.path.exists("GFG1")  # Check if directory exists

True

In [91]:
os.path.getsize("GFG1")  # Get size of directory

0

In [ ]:
#bulk create files in a directory
for i in range(4):
    name=f"GFG1/subdir1/file {i}"
    os.mkdir(name)

In [102]:
os.listdir("GFG1/subdir1")  # List files in the directory

['file 0', 'file 1', 'file 2', 'file 3', 'file 4']

In [105]:
os.mkdir('data')  # Create a directory named 'data'

for i in range(5):
    name= f"data/file_{i}.txt"
    f =open(name,'w')
    f.write(f"This is file {i}\n")
    f.close()  # Close the file after writing

In [106]:
for i in os.listdir("data"):
    name=f"data/{i}"
    f=open(name, 'r')
    print(f.read())  # Read and print the content of each file
    f.close()  # Close the file after reading

This is file 0

This is file 1

This is file 2

This is file 3

This is file 4



In [ ]:
for i in os.listdir("data"):
    if i.endswith(".txt"):
        name=f"data/{i}"
        f=open(name, 'r')
        print(f.read())  # Read and print the content of each file
        f.close()  # Close the file after reading

This is file 0

This is file 1

This is file 2

This is file 3

This is file 4



: 